New functions
centre-for-humanities-computing/conspiracies pull request #12
Opened 2022-04-04 12:42 UTC by esborisova

There are several things which still have to be added/checked:

1. Stephan assumed that there might be several spans as an output from `most_common_ancestor` function. I put the length check just in case. We can remove it if not relevant.
2. Issue with conj relation. I will have a look at it and if required find out how to split conj as heads.
3. Apply functions to the output from triplets extraction. 
4. Create the pipeline for frequency count and lists creation.

2022-04-05 09:03 UTC, KennethEnevoldsen requested changes
I few functions implement existing functionality. I would remove these. 

I would also rename the pull request to a more informative name (e.g. Add head word extraction)

2022-04-05 09:03 UTC, KennethEnevoldsen commented on tests/test_extract_heads.py
> +    Span.set_extension("most_common_ancestor", getter=most_common_ancestor)
I recommend creating a function called set_extensions() which sets this both on the Doc, Span and Token.

2022-04-05 09:03 UTC, KennethEnevoldsen commented on tests/test_extract_heads.py
> +def test_ents_check():
Given the above comment, I would remove this test along with the function.

2022-04-05 09:03 UTC, KennethEnevoldsen commented on tests/test_extract_heads.py
> +def test_ents_extractor():
Given the above comment, I would remove this test along with the function.

2022-04-05 11:20 UTC, esborisova commented on src/conspiracies/extract_heads.py
> +    return False
But we talked about filtering heads which are not entities with `filter()`.  Now I am not sure I understand how we will filter those from the list of spans.

2022-04-05 11:22 UTC, esborisova commented on src/conspiracies/extract_heads.py
> +    return doc[token.i:token.i + 1]
I only found how to return noun chunks on the `doc` level. I have not found any examples on how to normalize a token to a noun chunk. Can we actually do that within this function?

2022-04-05 11:24 UTC, esborisova commented on src/conspiracies/extract_heads.py
> +      raise ValueError
Is it possible to get several ancestors (headwords) at this point? 
If yes, then may be we should also check that only 1 head is returned (as the aim to get a single one per span)?

2022-04-05 13:01 UTC, KennethEnevoldsen commented on src/conspiracies/extract_heads.py
> +    return False
Ah yes, we did.

Keep this function and add the attribute:
```
span._.contains_ents
```
However you will have to fix the function such that it checks if a span has an ent. Right now it e.g. does not work for:
```
doc = nlp("hello my name is Kenneth")
span = doc[:]
```

2022-04-05 13:03 UTC, esborisova commented
In `set_extentions()` I am not sure about setting them for Token. I assumed the procedure is the same as for Span. 
I also do not know how to call Doc, Span and Token in type hints here `level:List[?]  `.

2022-04-05 13:22 UTC, KennethEnevoldsen requested changes
Looking better! A few more corrections.

Let me know what you think about the component.


You should format your code using black (guide and explanation [here](https://www.geeksforgeeks.org/python-code-formatting-using-black/)) - you can also set it up such that it formats when you save your file in vs code (I can help you with that if you want)

2022-04-05 13:22 UTC, KennethEnevoldsen commented on src/conspiracies/extract_heads.py
> +def normalize_token_to_span(token: Token, normalize_to_entity: bool = False) -> Span:
Still missing normalize_to_noun_chunk

2022-04-05 13:22 UTC, KennethEnevoldsen commented on src/conspiracies/extract_heads.py
> +def set_extensions(extention_name: str, extention: Callable, levels: list):
remove levels and simply add it to all. I was just thinking of using this function to set all the relevant extensions (not a specific one) so you should also remove extention_name, and extention.

Ideally, this should be implemented as a component similar to e.g. [textdescriptives](https://github.com/HLasse/TextDescriptives/blob/master/textdescriptives/components/readability.py). You can give it a try (there is a guide on how to do it [here](https://spacy.io/usage/processing-pipelines#custom-components)), but otherwise we can take a look at it together or I can reformulate this set extension into a component?

2022-04-05 13:22 UTC, KennethEnevoldsen commented on tests/test_extentions.py
> +    assert Token.has_extension("most_common_ancestor")
It is probably better to test:
```python
doc = nlp(...)
assert isinstance(doc._.most_common_ancestor, Span)
assert isinstance(doc[0]._.most_common_ancestor, Span) #token
assert isinstance(doc[0:2]._.most_common_ancestor, Span) #span
```

2022-04-05 13:22 UTC, KennethEnevoldsen commented on tests/test_extentions.py
> +    assert Token.has_extension("most_common_ancestor")
as this test that 1) the extension is set, 2) that the output is the correct format, and 3) that the function computes.

2022-04-05 13:22 UTC, KennethEnevoldsen commented on tests/test_extract_heads.py
> +    pipe = nlp.pipe(test_sents)
No need to create a pipe for one document.

```suggestion
    doc = nlp(text)
```

2022-04-05 13:22 UTC, KennethEnevoldsen commented on tests/test_extract_heads.py
> +    test_sents = ["Mette Frederiksen is the Danish politician."]
```suggestion
    text = "Mette Frederiksen is the Danish politician."
```

2022-04-05 13:22 UTC, KennethEnevoldsen commented on tests/test_extract_heads.py
> +            assert headword.text == "Frederiksen"
```suggestion
    for span in doc._.relation_head:
        headword = span._.most_common_ancestor

        assert isinstance(headword, Span)
        assert headword.text == "Frederiksen"
```

2022-04-05 13:49 UTC, esborisova commented on src/conspiracies/extract_heads.py
> +def normalize_token_to_span(token: Token, normalize_to_entity: bool = False) -> Span:
I left this comment earlier:
"I only found how to return noun chunks on the doc level. I have not found any examples on how to normalize a token to a noun chunk. Can we actually do that within this function?"

2022-04-05 13:51 UTC, esborisova commented on src/conspiracies/extract_heads.py
> +def set_extensions(extention_name: str, extention: Callable, levels: list):
I can give it a try.  In case it is unsuccessful, we can either have a look at it together or you will go ahead and make a component.

2022-04-05 13:57 UTC, KennethEnevoldsen commented
> In set_extentions() I am not sure about setting them for Token. I assumed the procedure is the same as for Span.
You can use the same trick as you use in normalize to span ;) 

> I also do not know how to call Doc, Span and Token in type hints here levels: List[?] .
If your list can contain multiple elements you can use Union `Union[Token, Span, Doc]`
e.g.
`List[Union[Token, Span, Doc]]` or `Union[List[Token], List[Span], List[Doc]]`
The only different here being that the first one says that the list should contain either a token span or docs (can contain multiple types) while the second says that it should be a List containing only tokens, or only span or only docs.

2022-04-07 11:57 UTC, esborisova commented
I managed to make it work as a component but I have several issues:

1. `@Language.component` gives me an Attribute error, while `@Language.factory` works fine. I use it but may be it is a wrong approach.  
2. How can I access functions' parameters? F.ex., I cannot set 'normalize_token_to_entity' in `._.normalize_token_to_span`.
There is `default_config` param in  `@Language.factory`. But it does not work for some reason when I use it. 
3. Should `contains_ents()' be just the function not a component?  Otherwise, I cannot use it with `filter()`.  
4. If a function can be used for both `Doc` and `Span` should I define input args as `Union[Doc, Span]`?
5. I have problems while running pytest `def test_headword():`. You suggested to use simply:
`text = "Mette Frederiksen is the Danish politician."
doc = nlp(text)
for span in doc._.relation_head:
headword = span._.most_common_ancestor'

However, this does not work. In the examples for RelationExtraction Lasse always uses a list of sentences as an input and `pipe = nlp.pipe(test_sents)`.

2022-04-08 07:12 UTC, esborisova commented
It is not clear what you mean in here

2022-04-08 07:14 UTC, esborisova commented
It is not clear what you mean here

> I recommend don't set them in a loop as the function shouldn't all be set the same way on all objects.
> The normalize_to_span function I think is best set as the extension as_span e.g. Token._.as_span

Do you want 3 different functions `normalize_to_span`, `normalize_to_entity`, `normalize_to_noun_chunk`?

2022-04-08 07:51 UTC, esborisova commented
@HLasse This still does not work :( 
`>       for span in doc._.relation_head:
       TypeError: 'NoneType' object is not iterable`

2022-04-08 07:55 UTC, KennethEnevoldsen commented
Hmm a Yea right. I want something like this:

Token._.to_span

Where when you add the pipe you can specify normalize_to_entity and normalize_to_noun_chunk.

E.g. nlp.add_pipe('headword_extraction', config={'normalize_to_entity'=True})

Does this make sense?

2022-04-08 08:05 UTC, esborisova commented
Then those still can be args for a single function `normalize_to_span`. And if needed, one can set those in config to `True`.  

Or.....you want sep functions which are called inside the body of 'to_span' function when `normalize_to_entity` and `normalize_to_noun_chunk` are set to `True`? 
Smth like:
```
def normalize_to_span(token: Token, normalize_to_entity: bool = False, normalize_to_noun_chunk: bool = False):
    if normalize_to_entity == True:
       ent = to_ent(token)
  if normalize_to_noun_chunk == True:
      noun_chunk = to_noun_chunk(token)
.............
```

2022-04-08 08:13 UTC, esborisova commented
I also do not understand why even though I black formatted files, black test fails on git.

2022-04-08 08:29 UTC, martbern commented
> I also do not understand why even though I black formatted files, black test fails on git.

The black-formatting error is probably due to a version mismatch between the github action and your local version. 22.3.0 is the GH action here, which matches the requirements - so `pip install -r requirements.txt` followed by `black .` should fix it 👍

2022-04-08 11:52 UTC, esborisova commented
There is a problem with `normalize_to_entity`. If a token is not an entity, the function returns `None` and unsurprisingly `len()` cannot be applied. We do not need to normalize heads to the whole entity for the current task. But I think we still need to decide how to deal with it :) 
I also downgraded `black` to 22.1.0 as in requirements. Hope, the test won't fail.

2022-04-08 12:01 UTC, esborisova commented
@KennethEnevoldsen  I pushed the new version of scripts. There is no option to request a review since one is still in the queue. 

There is a problem with `normalize_to_entity()`. If a token is NOT an entity, it returns  `None`. Consequently, `len()` cannot be applied in ` most_common_ancestor()` (line 168). We do not need this functionality for the current task. But still I think this should be solved. May be check if empty instead of `len()`  and return an empty str instead of None?

I also downgraded black to the version specified in req-s. Hope, the test won't fail.

2022-04-11 11:31 UTC, KennethEnevoldsen commented
@martbern 22.3.0 is stable? I have also specifically fixed the version in both requirements.txt and the workflow.

Regardless the black part is quite easy to fix when everything else is ready so wouldn't worry too much about it.

2022-04-11 11:43 UTC, KennethEnevoldsen commented on tests/test_normalize_to_ent.py
> +import spacy
test_normalize_to_ent, test_normalize_to_noun_chunk, test_normalize_to_span, can reasonably be moved together in one file called "test_normalize_to_span" with three tests in it.

2022-04-11 11:43 UTC, KennethEnevoldsen commented on tests/test_head_extractor.py
> +            assert headword.text == "Frederiksen"
There is no reason to use a pipe here. Especially since you are asserting something which only refers to the specific document i.e. "Frederiksen" is not the headword text of all headwords.

2022-04-11 11:43 UTC, KennethEnevoldsen commented on tests/test_extentions.py
> +    assert isinstance(doc[0]._.normalize_to_span, Span)
```suggestion
```
I assume this shouldn't be here?

2022-04-11 11:43 UTC, KennethEnevoldsen commented on tests/test_extentions.py
> +    assert isinstance(doc[:]._.most_common_ancestor, Span)  # Doc
```suggestion
    assert isinstance(doc._.most_common_ancestor, Span)  # Doc
```
I assume this is what you want to test?

2022-04-11 11:43 UTC, KennethEnevoldsen commented on src/conspiracies/heads_extract_component.py
> +                    Span.set_extension(extention, getter=function)
You are creating a for loop for two elements with one exception. It would be cleaner to set the extensions twice. It would also allow you to set the:

`normalize_to_span` on both doc and span as well. Which I would do.

2022-04-11 11:43 UTC, KennethEnevoldsen commented on src/conspiracies/heads_extract_component.py
> +            "normalize_to_span",
Would change `normalize_to_span` to `to_span`, such that the usage becomes `token._.to_span` if you disagree then just keep it as is.

2022-04-11 12:00 UTC, esborisova commented on tests/test_head_extractor.py
> +            assert headword.text == "Frederiksen"
@HLasse  promised to fix the issue with pipe and list input.

2022-04-11 14:45 UTC, KennethEnevoldsen commented on tests/test_normalize_to_span.py
> +    nlp.add_pipe("heads_extraction", config={"normalize_to_entity": True})
```suggestion
    nlp.add_pipe("heads_extraction", config={"normalize_to_entity": True, force=True})
```

2022-04-11 14:49 UTC, KennethEnevoldsen commented on src/conspiracies/heads_extract_component.py
> +            Span.set_extension("most_common_ancestor", getter=self.most_common_ancestor)
```suggestion
    def __init__(
        self,
        nlp: Language,
        name: str,
        raise_error: bool,
        normalize_to_entity: bool,
        normalize_to_noun_chunk: bool,
        force: bool = True
    ):
        """Initialise components"""

        self.raise_error = raise_error
        self.normalize_to_entity = normalize_to_entity
        self.normalize_to_noun_chunk = normalize_to_noun_chunk

        if not Token.has_extension("to_span") or force:
            Token.set_extension("to_span", getter=self.to_span, force=force)
        if not Span.has_extension("to_span") or force:
            Span.set_extension("to_span", getter=lambda span: span, force=force)
        if not Doc.has_extension("to_span") or force:
            Doc.set_extension("to_span", getter=lambda doc: doc[:], force=force)

        if not Doc.has_extension("most_common_ancestor") or force:
            Doc.set_extension(
                "most_common_ancestor",
                getter=lambda doc: self.most_common_ancestor(doc[:], force=force),
            )
        if not Span.has_extension("most_common_ancestor") or force:
            Span.set_extension("most_common_ancestor", getter=self.most_common_ancestor, force=force)
```

2022-04-11 14:50 UTC, KennethEnevoldsen commented on src/conspiracies/heads_extract_component.py
> +)
```suggestion
        "normalize_to_noun_chunk": False,
        "force": True
    },
)
```

2022-04-11 14:51 UTC, KennethEnevoldsen commented on src/conspiracies/heads_extract_component.py
> +)
Added force arguments to forcefully overwrite the extension.

2022-04-11 14:51 UTC, KennethEnevoldsen commented on src/conspiracies/heads_extract_component.py
> +    )
Added force arguments to forcefully overwrite the extension.

2022-04-12 08:30 UTC, esborisova commented on src/conspiracies/extract_heads.py
> +def normalize_token_to_span(token: Token, normalize_to_entity: bool = False) -> Span:
we already have it :)

2022-04-12 08:39 UTC, esborisova commented
1. If a function returns a class, how to define it in type hints (in `create_component()`)?
2.  We still have problem when applying `to_noun_chunk` in `most_common_ancestor()`. If None is returned, `len()` results in error.

2022-04-12 12:10 UTC, KennethEnevoldsen commented on tests/test_normalize_to_span.py
> +    normalized_token = doc[:]._.to_span  # Doc
```suggestion
    normalized_token = doc._.to_span  # Doc
```
Didn't we already change this?

2022-04-12 12:10 UTC, KennethEnevoldsen commented on tests/test_normalize_to_span.py
> +def test_normalize_to_span():
You have two tests called the same thing. You should change the name of one

2022-04-12 12:11 UTC, KennethEnevoldsen commented
> * If a function returns a class, how to define it in type hints (in `create_component()`)?
You can simply put the class:
```python
create_component() -> Component:
    # your code
```
Where Component is your class the create_component outputs.

> * We still have problem while applying `to_noun_chunk` in `most_common_ancestor()`. If None is returned, `len()` results in error.
I have added some corrections on this. Basically the solution is to only return if there is a value otherwise you fall back to the token normalisation

2022-04-12 12:19 UTC, esborisova commented on tests/test_normalize_to_span.py
> +    normalized_token = doc[:]._.to_span  # Doc
not sure, probably in another test.

2022-04-12 12:21 UTC, esborisova commented on tests/test_normalize_to_span.py
> +def test_normalize_to_span():
oh, fixed.

2022-04-12 12:41 UTC, KennethEnevoldsen approved these changes
Assuming the tests pass this looks good to merge

Edit: Regarding black linting I can do that quickly

2022-04-12 12:41 UTC, KennethEnevoldsen commented on src/conspiracies/heads_extract_component.py
> +    """
```suggestion
    A class for extracting headwords from a given text document.z

    Args:
        nlp (Language): Language processing pipelines.
        name (str): The instance name of the component in the pipeline.

    Attributes:
        raise_error (bool): If True, raises warning message in case no ancestor is found within a span.
        normalize_to_entity (bool): If True, normalizes a token to an entity.
        normalize_to_noun_chunk (bool): If True, normalizes a token to a noun chunk.
    """
```

2022-04-12 12:46 UTC, esborisova commented
Sounds great! Go for it!

2022-04-12 13:13 UTC, merged