coref_resolved added to main branch clone
centre-for-humanities-computing/conspiracies pull request #19
Opened 2022-04-13 12:16 UTC by linguist89

I have now added the coref_resolved attribute at the Doc level from a clone of the main branch, so all other issues should be solved.

2022-04-13 12:25 UTC, KennethEnevoldsen requested changes
Looks good, but still a few things missing:
- [ ] It is missing a test convincing me that it works as intended.
- [x] We would ideally want to do this on a Span level as well.
- [ ] The code needs to be formatted to black, this can be done using:
```
# in the repository
pip install -r requirements.txt
# autoformat using black
black . 
```

2022-04-13 12:25 UTC, KennethEnevoldsen commented on src/conspiracies/coref/CoreferenceComponent.py
> +        if not Span.has_extension("coref_cluster"):
Why change it from coref_clusters? Seems like it is nice that is consistent with the Doc level?

2022-04-13 12:25 UTC, KennethEnevoldsen commented on src/conspiracies/coref/CoreferenceComponent.py
> +            doc._.resolved_coref = ''.join(resolved)
Add this an extension to the Doc. No reason to compute this for all docs if not needed.

2022-04-13 13:27 UTC, linguist89 commented on src/conspiracies/coref/CoreferenceComponent.py
> +        if not Span.has_extension("coref_cluster"):
Done

2022-04-13 13:27 UTC, linguist89 commented on src/conspiracies/coref/CoreferenceComponent.py
> +            doc._.resolved_coref = ''.join(resolved)
Done

2022-04-14 10:02 UTC, KennethEnevoldsen requested changes

2022-04-14 10:02 UTC, KennethEnevoldsen commented on tests/test_coref_component.py
> +    assert isinstance(doc._.resolve_coref, str)
I would like to see that this actually resolved the coref as intended. I.e.

doc._.resolve_coref == "the desired string"

As there might naturally be errors in the coref res. it is perfectly valid to set the coref clusters manually as we are testing the functions here (not the model).

2022-04-14 10:05 UTC, KennethEnevoldsen commented
Hmm, feel like these are still unresolved:
- [ ] It is missing a test convincing me that it works as intended (see comment).
- [ ] Add the coref_resolved as a Span extension as well.

2022-04-16 10:49 UTC, KennethEnevoldsen requested changes
see unresolved comment above. (this is just because I get pinged for not completing the review)

2022-04-22 12:33 UTC, KennethEnevoldsen approved these changes
Looks good will merge it in

2022-04-22 12:33 UTC, merged