add: relation extraction module
centre-for-humanities-computing/conspiracies pull request #35
Opened 2022-05-04 15:36 UTC by HLasse

2022-05-04 17:57 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-64%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/conspiracies</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/HeadWordExtractionComponent.py">HeadWordExtractionComponent.py</a></td><td>59</td><td>3</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/HeadWordExtractionComponent.py#L155-L161">155&ndash;161</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/__init__.py">__init__.py</a></td><td>3</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/download.py">download.py</a></td><td>39</td><td>1</td><td>97%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/download.py#L60">60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/wordpiece_length_normalization.py">wordpiece_length_normalization.py</a></td><td>38</td><td>1</td><td>97%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/wordpiece_length_normalization.py#L50">50</a></td></tr><tr><td colspan="5"><b>src/conspiracies/coref</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/coref/CoreferenceComponent.py">CoreferenceComponent.py</a></td><td>76</td><td>4</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/coref/CoreferenceComponent.py#L198-L202">198&ndash;202</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/coref/CoreferenceModel.py">CoreferenceModel.py</a></td><td>26</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/coref/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td colspan="5"><b>src/conspiracies/relationextraction</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py">dataset.py</a></td><td>131</td><td>79</td><td>40%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L13-L23">13&ndash;23</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L33-L46">33&ndash;46</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L49-L54">49&ndash;54</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L57">57</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L60">60</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L63-L83">63&ndash;83</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L86">86</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L89-L112">89&ndash;112</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L119-L128">119&ndash;128</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L131-L136">131&ndash;136</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L139">139</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L142">142</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L145-L154">145&ndash;154</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L166">166</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/dataset.py#L184">184</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/extract.py">extract.py</a></td><td>158</td><td>106</td><td>33%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/extract.py#L12-L100">12&ndash;100</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/extract.py#L104-L192">104&ndash;192</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/extract.py#L196-L281">196&ndash;281</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/extract.py#L369">369</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/knowledge_triplets.py">knowledge_triplets.py</a></td><td>51</td><td>4</td><td>92%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/093ff4422b5040cbc12c883c1b76640bd1dc673b/src/conspiracies/relationextraction/knowledge_triplets.py#L58">58</a>, <a href="https://github.com/centre-for-humanities-comput [...]

2022-05-05 08:42 UTC, KennethEnevoldsen requested changes
There are some files that I suspect should be deleted:
- `CaRB_dev.tsv`
- `CaRB_test.tsv`

Docstrings to many of the `carb/*` files would be nice for the future

As we talked about (but is not for this PR), we should create issues for:
- [ ] Batches currently only work across sentences in a single doc not across sentences in multiple docs
- [ ] We have not set a sentence extension for the relation extractions

2022-05-05 08:42 UTC, KennethEnevoldsen commented on .gitignore
> +.DS_Store
```suggestion
# MacOS
.DS_Store
```

2022-05-05 08:42 UTC, KennethEnevoldsen commented on README.md
> +print(final_result ["extraction_3"])
What is extraction 3?

2022-05-05 08:42 UTC, KennethEnevoldsen commented on src/conspiracies/relationextraction/carb/argument.py
> +import nltk
Is this for reading the gold data?

2022-05-05 08:53 UTC, KennethEnevoldsen commented on src/conspiracies/relationextraction/knowledge_triplets.py
> +    """A class for extracting triplets from a given text document.
```suggestion
class KnowledgeTriplets:
    """A class for extracting triplets from a given text document.
```

2022-05-05 08:53 UTC, KennethEnevoldsen commented on src/conspiracies/relationextraction/knowledge_triplets.py
> +    """
```suggestion
        device: A boolean indicating whether to train a model on GPU or CPU.
    """
```

2022-05-05 08:53 UTC, KennethEnevoldsen commented on src/conspiracies/relationextraction/knowledge_triplets.py
> +        batch_size: An integer indicating the number of samples that will be propogated through the network.
```suggestion
    Example:
       >>> re = KnowledgeTriplets(model_path = None)
       >>> extracted_triplets = re.extract_relations(list_of_sent)

    Args:
        model_path: Path to a model (str, optional).

    Attributes:
        batch_size: An integer indicating the number of samples that will be propogated through the network.
```

2022-05-05 08:53 UTC, KennethEnevoldsen commented on src/conspiracies/relationextraction/other/align.py
> +"""
```suggestion
"""
Copyright (C) 2022 Explosion AI and Center for Humanities Computing Aarhus - All Rights Reserved
You may use, distribute and modify this code under the
terms of the MIT license.
Original code from:
https://raw.githubusercontent.com/explosion/spacy-transformers/master/spacy_transformers/align.py

The following functions are copied/modified from their code:
[...]
To avoid clashing torch versions.
"""
```

Remove chcaa if we haven't made any changes

2022-05-05 08:53 UTC, KennethEnevoldsen commented on tests/test_relationextraction_component.py
> +        print(d.text, "\n", d._.relation_triplets)
We should probably do a bit more testing here. For instance, if I want to change how the batches work I want to make sure that the extractions are the same.

So:
- [ ] add check output is correct (with and without multiple sentences)
- [ ] check type of output is consistent
- [ ] check that it works with an empty string

2022-08-25 13:31 UTC, KennethEnevoldsen commented
@HLasse <3

2022-08-25 14:06 UTC, HLasse commented
TODO:
[ ] - moar tests

2022-08-26 09:08 UTC, HLasse commented
Good call with proper tests - turns out _not_ using `nlp.pipe` didn't work. Deleted a bunch of unused files and wrote some proper tests too. 
We might need to discuss output of empty docs/with no triplets (currently `None` instead of `[]`

2022-08-26 09:13 UTC, KennethEnevoldsen commented
@HLasse will you be at the friday bar? We can discuss it there

2022-08-26 09:22 UTC, KennethEnevoldsen commented on src/conspiracies/HeadWordExtractionComponent.py
> +            most_common_ancestor = span[0]
Is this merged from main?

2022-08-26 09:22 UTC, KennethEnevoldsen commented on src/conspiracies/relationextraction/dataset.py
> +import numpy as np
A docstring here would be nice to explain why the "EvalDataset" is here.

2022-08-26 09:22 UTC, KennethEnevoldsen commented on src/conspiracies/relationextraction/knowledge_triplets.py
> +        model_path: Path to a model (str, optional).
Apparently, the recommendation is to have this in the __init__:
https://stackoverflow.com/questions/37019744/is-there-a-consensus-what-should-be-documented-in-the-classes-and-init-docst

2022-08-26 09:41 UTC, KennethEnevoldsen commented
I have fixed the error pertaining to the tests (due to: https://github.com/allenai/allennlp/issues/5666)

2022-08-26 09:47 UTC, KennethEnevoldsen reviewed
In general only minor issues. When we have resolved the list/None issue feel free to merge it in.

2022-08-26 09:53 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-75%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/conspiracies</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/HeadWordExtractionComponent.py">HeadWordExtractionComponent.py</a></td><td>62</td><td>3</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/HeadWordExtractionComponent.py#L159-L165">159&ndash;165</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/__init__.py">__init__.py</a></td><td>3</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/download.py">download.py</a></td><td>39</td><td>1</td><td>97%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/download.py#L60">60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/wordpiece_length_normalization.py">wordpiece_length_normalization.py</a></td><td>38</td><td>1</td><td>97%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/wordpiece_length_normalization.py#L50">50</a></td></tr><tr><td colspan="5"><b>src/conspiracies/coref</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/coref/CoreferenceComponent.py">CoreferenceComponent.py</a></td><td>76</td><td>4</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/coref/CoreferenceComponent.py#L198-L202">198&ndash;202</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/coref/CoreferenceModel.py">CoreferenceModel.py</a></td><td>26</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/coref/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td colspan="5"><b>src/conspiracies/relationextraction</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/dataset.py">dataset.py</a></td><td>37</td><td>2</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/dataset.py#L18">18</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/dataset.py#L36">36</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/extract.py">extract.py</a></td><td>158</td><td>107</td><td>32%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/extract.py#L12-L100">12&ndash;100</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/extract.py#L104-L192">104&ndash;192</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/extract.py#L196-L281">196&ndash;281</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/extract.py#L342">342</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/extract.py#L369">369</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/knowledge_triplets.py">knowledge_triplets.py</a></td><td>51</td><td>3</td><td>94%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/knowledge_triplets.py#L52">52</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/knowledge_triplets.py#L110">110</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/knowledge_triplets.py#L114">114</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/model.py">model.py</a></td><td>161</td><td>67</td><td>58%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/model.py#L129-L172">129&ndash;172</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/model.py#L202-L222">202&ndash;222</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/model.py#L235-L273">235&ndash;273</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/model.py#L276-L278">276&ndash;278</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/model.py#L281-L286">281&ndash;286</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/model.py#L292-L295">292&ndash;295</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/util.py">util.py</a></td><td>59</td><td>3</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1725c3d9c/src/conspiracies/relationextraction/util.py#L54">54</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/b432fb271b5ca637a973dc9a3f9583b1 [...]

2022-08-26 09:57 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-75%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/conspiracies</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/HeadWordExtractionComponent.py">HeadWordExtractionComponent.py</a></td><td>62</td><td>3</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/HeadWordExtractionComponent.py#L159-L165">159&ndash;165</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/__init__.py">__init__.py</a></td><td>3</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/download.py">download.py</a></td><td>39</td><td>1</td><td>97%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/download.py#L60">60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/wordpiece_length_normalization.py">wordpiece_length_normalization.py</a></td><td>38</td><td>1</td><td>97%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/wordpiece_length_normalization.py#L50">50</a></td></tr><tr><td colspan="5"><b>src/conspiracies/coref</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/coref/CoreferenceComponent.py">CoreferenceComponent.py</a></td><td>76</td><td>4</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/coref/CoreferenceComponent.py#L198-L202">198&ndash;202</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/coref/CoreferenceModel.py">CoreferenceModel.py</a></td><td>26</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/coref/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td colspan="5"><b>src/conspiracies/relationextraction</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/dataset.py">dataset.py</a></td><td>37</td><td>2</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/dataset.py#L18">18</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/dataset.py#L36">36</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/extract.py">extract.py</a></td><td>158</td><td>107</td><td>32%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/extract.py#L12-L100">12&ndash;100</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/extract.py#L104-L192">104&ndash;192</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/extract.py#L196-L281">196&ndash;281</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/extract.py#L342">342</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/extract.py#L369">369</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/knowledge_triplets.py">knowledge_triplets.py</a></td><td>51</td><td>3</td><td>94%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/knowledge_triplets.py#L52">52</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/knowledge_triplets.py#L110">110</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/knowledge_triplets.py#L114">114</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/model.py">model.py</a></td><td>161</td><td>67</td><td>58%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/model.py#L129-L172">129&ndash;172</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/model.py#L202-L222">202&ndash;222</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/model.py#L235-L273">235&ndash;273</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/model.py#L276-L278">276&ndash;278</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/model.py#L281-L286">281&ndash;286</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/model.py#L292-L295">292&ndash;295</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/util.py">util.py</a></td><td>59</td><td>3</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d88a440342/src/conspiracies/relationextraction/util.py#L54">54</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/f21c783d8fdd4d7b341531c838f5e5d8 [...]

2022-08-26 10:07 UTC, HLasse commented
Agreed, with the None/empty list issue. Has been fixed. 
Coref checks still fail on my end - will you take a look?

2022-08-26 10:11 UTC, HLasse commented
Maybe we should run the CI tests on less platforms - takes a while!

2022-08-26 10:17 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-76%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/conspiracies</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/HeadWordExtractionComponent.py">HeadWordExtractionComponent.py</a></td><td>62</td><td>3</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/HeadWordExtractionComponent.py#L159-L165">159&ndash;165</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/__init__.py">__init__.py</a></td><td>3</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/download.py">download.py</a></td><td>39</td><td>1</td><td>97%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/download.py#L60">60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/wordpiece_length_normalization.py">wordpiece_length_normalization.py</a></td><td>38</td><td>1</td><td>97%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/wordpiece_length_normalization.py#L50">50</a></td></tr><tr><td colspan="5"><b>src/conspiracies/coref</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/coref/CoreferenceComponent.py">CoreferenceComponent.py</a></td><td>76</td><td>4</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/coref/CoreferenceComponent.py#L198-L202">198&ndash;202</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/coref/CoreferenceModel.py">CoreferenceModel.py</a></td><td>26</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/coref/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td colspan="5"><b>src/conspiracies/relationextraction</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/dataset.py">dataset.py</a></td><td>37</td><td>2</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/dataset.py#L18">18</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/dataset.py#L36">36</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/extract.py">extract.py</a></td><td>158</td><td>106</td><td>33%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/extract.py#L12-L100">12&ndash;100</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/extract.py#L104-L192">104&ndash;192</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/extract.py#L196-L281">196&ndash;281</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/extract.py#L369">369</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/knowledge_triplets.py">knowledge_triplets.py</a></td><td>51</td><td>3</td><td>94%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/knowledge_triplets.py#L50">50</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/knowledge_triplets.py#L108">108</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/knowledge_triplets.py#L112">112</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/model.py">model.py</a></td><td>161</td><td>67</td><td>58%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/model.py#L129-L172">129&ndash;172</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/model.py#L202-L222">202&ndash;222</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/model.py#L235-L273">235&ndash;273</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/model.py#L276-L278">276&ndash;278</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/model.py#L281-L286">281&ndash;286</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/model.py#L292-L295">292&ndash;295</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/util.py">util.py</a></td><td>59</td><td>3</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/util.py#L54">54</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241ab7/src/conspiracies/relationextraction/util.py#L68">68</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/be7e4c139ea27a50ecc224f609f62f4115241 [...]

2022-08-26 10:24 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-76%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/conspiracies</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/HeadWordExtractionComponent.py">HeadWordExtractionComponent.py</a></td><td>62</td><td>3</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/HeadWordExtractionComponent.py#L159-L165">159&ndash;165</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/__init__.py">__init__.py</a></td><td>3</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/download.py">download.py</a></td><td>39</td><td>1</td><td>97%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/download.py#L60">60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/wordpiece_length_normalization.py">wordpiece_length_normalization.py</a></td><td>38</td><td>1</td><td>97%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/wordpiece_length_normalization.py#L50">50</a></td></tr><tr><td colspan="5"><b>src/conspiracies/coref</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/coref/CoreferenceComponent.py">CoreferenceComponent.py</a></td><td>76</td><td>4</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/coref/CoreferenceComponent.py#L198-L202">198&ndash;202</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/coref/CoreferenceModel.py">CoreferenceModel.py</a></td><td>26</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/coref/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td colspan="5"><b>src/conspiracies/relationextraction</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/dataset.py">dataset.py</a></td><td>36</td><td>2</td><td>94%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/dataset.py#L18">18</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/dataset.py#L36">36</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/extract.py">extract.py</a></td><td>158</td><td>106</td><td>33%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/extract.py#L12-L100">12&ndash;100</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/extract.py#L104-L192">104&ndash;192</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/extract.py#L196-L281">196&ndash;281</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/extract.py#L369">369</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/knowledge_triplets.py">knowledge_triplets.py</a></td><td>51</td><td>3</td><td>94%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/knowledge_triplets.py#L50">50</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/knowledge_triplets.py#L108">108</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/knowledge_triplets.py#L112">112</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/model.py">model.py</a></td><td>161</td><td>67</td><td>58%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/model.py#L129-L172">129&ndash;172</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/model.py#L202-L222">202&ndash;222</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/model.py#L235-L273">235&ndash;273</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/model.py#L276-L278">276&ndash;278</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/model.py#L281-L286">281&ndash;286</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/model.py#L292-L295">292&ndash;295</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/util.py">util.py</a></td><td>59</td><td>3</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/util.py#L54">54</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384cfe/src/conspiracies/relationextraction/util.py#L68">68</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/73c9d015ca19231c75439af8ffa8c4df73384 [...]

2022-08-26 10:47 UTC, KennethEnevoldsen commented
<!-- Pytest Coverage Comment: pytest-coverage -->
<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-76%25-yellow.svg" /></a><br/><details><summary>Coverage Report</summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>src/conspiracies</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/HeadWordExtractionComponent.py">HeadWordExtractionComponent.py</a></td><td>62</td><td>3</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/HeadWordExtractionComponent.py#L159-L165">159&ndash;165</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/__init__.py">__init__.py</a></td><td>3</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/download.py">download.py</a></td><td>39</td><td>1</td><td>97%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/download.py#L60">60</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/wordpiece_length_normalization.py">wordpiece_length_normalization.py</a></td><td>38</td><td>1</td><td>97%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/wordpiece_length_normalization.py#L50">50</a></td></tr><tr><td colspan="5"><b>src/conspiracies/coref</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/coref/CoreferenceComponent.py">CoreferenceComponent.py</a></td><td>76</td><td>4</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/coref/CoreferenceComponent.py#L198-L202">198&ndash;202</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/coref/CoreferenceModel.py">CoreferenceModel.py</a></td><td>26</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/coref/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td colspan="5"><b>src/conspiracies/relationextraction</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/__init__.py">__init__.py</a></td><td>2</td><td>0</td><td>100%</td><td>&nbsp;</td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/dataset.py">dataset.py</a></td><td>36</td><td>2</td><td>94%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/dataset.py#L18">18</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/dataset.py#L36">36</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/extract.py">extract.py</a></td><td>158</td><td>106</td><td>33%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/extract.py#L12-L100">12&ndash;100</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/extract.py#L104-L192">104&ndash;192</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/extract.py#L196-L281">196&ndash;281</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/extract.py#L369">369</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/knowledge_triplets.py">knowledge_triplets.py</a></td><td>51</td><td>3</td><td>94%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/knowledge_triplets.py#L50">50</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/knowledge_triplets.py#L108">108</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/knowledge_triplets.py#L112">112</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/model.py">model.py</a></td><td>161</td><td>67</td><td>58%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/model.py#L129-L172">129&ndash;172</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/model.py#L202-L222">202&ndash;222</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/model.py#L235-L273">235&ndash;273</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/model.py#L276-L278">276&ndash;278</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/model.py#L281-L286">281&ndash;286</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/model.py#L292-L295">292&ndash;295</a></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/util.py">util.py</a></td><td>59</td><td>3</td><td>95%</td><td><a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/util.py#L54">54</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170e63/src/conspiracies/relationextraction/util.py#L68">68</a>, <a href="https://github.com/centre-for-humanities-computing/conspiracies/blob/0a3aae00917d031a5b54f53319be23f949170 [...]

2022-08-26 13:39 UTC, KennethEnevoldsen approved these changes

2022-08-26 13:40 UTC, merged